@baseUrl = http://localhost:3000
@apiUrl = https://covid-193.p.rapidapi.com


### API test Countries

GET {{apiUrl}}/countries
X-RapidAPI-Host: covid-193.p.rapidapi.com
X-RapidAPI-Key: 0d7c0b125amsh10015c2518910e5p12fb5fjsn0a60694a54eb

### API test Countries

GET {{apiUrl}}/statistics
X-RapidAPI-Host: covid-193.p.rapidapi.com
X-RapidAPI-Key: 0d7c0b125amsh10015c2518910e5p12fb5fjsn0a60694a54eb


###  Everything about cases in Japan

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/summary",
    "parameters": { "country": "Japan" }
}

###  Unkown country Middle Earth

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/summary",
    "parameters": { "country": "Middle Earth" }
}

### Total number of new cases in the South Korea

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/cases/total",
    "parameters": { "country": "S-Korea" }
}

### Number of cases per million in Nigeria

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/cases/million",
    "parameters": { "country": "Nigeria" }
}


### Number of active cases in the Netherlands

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/cases/active",
    "parameters": { "country": "Netherlands" }
}


### Number of new cases in Mexico

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/cases/new",
    "parameters": { "country": "Mexico" }
}


### Number of tests in India

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/tests",
    "parameters": { "country": "India" }
}


### Number of deaths in the USA

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/deaths",
     "parameters": { "country": "USA" }
}


### Population in Germany

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "country/population",
    "parameters": { "country": "Germany" }
}

### Total worldwide summary

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "total/summary"
}

### Total cases

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "total/cases"
}

### Total deaths

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "total/deaths"
}

### Total tests

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "total/tests"
}

### Currently not implemented: Comparison between France, Germany, and Spain

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "countries/cases",
    "parameters": { "countries": ["France", "Germany", "Spain"] }
}