@baseUrl = http://localhost:8888


###  Everything about cases in Japan

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_CASES",
    "parameters": { "country": "Japan" }
}

### Number of new cases in the South Korea

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_NEW_CASES",
    "parameters": { "country": "S-Korea" }
}

### Number of total cases in Germany

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_TOTAL_CASES",
    "parameters": { "country": "Germany" }
}


### Number of active cases in the Netherlands

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_ACTIVE_CASES",
    "parameters": { "country": "Netherlands" }
}


### Number of cases per million in Mexico

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_CASES_PER_MILLION",
    "parameters": { "country": "Mexico" }
}


### Number of tests in India

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_TESTS",
    "parameters": { "country": "India" }
}


### Number of deaths in the USA

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_DEATHS",
     "parameters": { "country": "USA" }
}


### Population in Germany

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRY_POPULATION",
    "parameters": { "country": "Germany" }
}


### Comparison between France, Germany, and Spain

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "COUNTRIES_CASES",
    "parameters": { "countries": ["France", "Germany", "Spain"] }
}

### Total worldwide summary

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "TOTAL_SUMMARY"
}

### Total cases

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "TOTAL_CASES"
}

### Total deaths

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "TOTAL_DEATHS"
}

### Total tests

POST {{baseUrl}}/
Content-Type: application/json

{
    "intent": "TOTAL_TESTS"
}